[package]
name = "contract-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.4.2", features = ["full", "sol-types"] }
alloy-primitives = "0.8.7"
eyre = "0.6.12"
tokio = { version = "1.40", features = ["full"] }
